language: python
python:
  - "3.4"
env:
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO
  - pip install -q -e .
before_script:

script:
  - python3.4 setup.py sdist
deploy:
  provider: releases
  api_key: "${API_KEY}"
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true