language: python
python:
  - "3.4"
env:
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO
  - pip install -q -e .
before_script:

script:
  - python3.4 setup.py sdist

before_deploy:
  - echo "deploying to GitHub releases"
deploy:
  provider: releases
  api_key: "${API_KEY}"
  file_glob: true
  file: "dist/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true