language: python
python:
  - "3.4"
env:
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:

script:
  - python3.4 setup.py sdist
deploy:
  provider: releases
  user: "GITHUB USERNAME"
  password: "GITHUB PASSWORD"
  file: "dist/django-rog-0.1.tar.gz"
  skip_cleanup: true
  on:
    tags: true